import React from 'react';
import { motion } from 'motion/react';
import { Target, Users, Rocket, Eye } from 'lucide-react';

export default function About() {
  return (
    <div className="pt-32 pb-20 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="max-w-3xl">
          <h1 className="text-4xl md:text-6xl font-bold mb-8 text-white tracking-tighter">Redefining Support for the AI Era.</h1>
          <p className="text-white/70 text-xl leading-relaxed mb-12 font-medium">
            CiteSupport was born out of a simple problem: businesses having too much documentation and too little time to answer customers accurately. 
            We built a platform that lets AI act as a second brain for your support team.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-12 mt-20">
          <AboutSection 
            icon={<Target className="w-8 h-8 text-white" />}
            title="Our Mission"
            content="To provide every company with an intelligent support agent that is as accurate as a human and fast as machine logic."
          />
          <AboutSection 
            icon={<Eye className="w-8 h-8 text-white" />}
            title="Our Vision"
            content="A world where support queries are resolved instantly, and human agents only step in for creative problem solving."
          />
        </div>

        <div className="mt-32 grid md:grid-cols-2 gap-12 border-t border-white/10 pt-20">
          <div>
            <h2 className="text-3xl font-bold mb-4 tracking-tight text-white">Transparent AI</h2>
            <p className="text-white/60 leading-relaxed font-medium">
              We believe AI should be a helper, not a black box. That's why every single response generated by CiteSupport comes with verifiable citations, linking directly back to your source material.
            </p>
          </div>
          <div>
            <h2 className="text-3xl font-bold mb-4 tracking-tight text-white">Enterprise Grade</h2>
            <p className="text-white/60 leading-relaxed font-medium">
              Security is at the core of everything we build. With multi-tenant isolation, your data is logically and physically separated from other organizations, ensuring complete privacy and compliance.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function AboutSection({ icon, title, content }: { icon: React.ReactNode, title: string, content: string }) {
  return (
    <div className="space-y-6">
      <div className="bg-white/5 border border-white/10 w-16 h-16 rounded-2xl flex items-center justify-center shadow-sm">
        {icon}
      </div>
      <h3 className="text-2xl font-bold text-white tracking-tight">{title}</h3>
      <p className="text-white/60 text-lg leading-relaxed font-medium">
        {content}
      </p>
    </div>
  );
}
